location = /login {
    proxy_pass http://127.0.0.1:1411;
    include /www/sites/auth.owmini.xyz/proxy/proxy-headers.inc;
    include /www/sites/auth.owmini.xyz/proxy/cookie-migration.inc;
}

location = /continue {
    proxy_pass http://127.0.0.1:1411;
    include /www/sites/auth.owmini.xyz/proxy/proxy-headers.inc;
    include /www/sites/auth.owmini.xyz/proxy/cookie-migration.inc;
}

location ^~ / {
    proxy_pass http://127.0.0.1:1411;
    include /www/sites/auth.owmini.xyz/proxy/proxy-headers.inc;
}
