// Single source of truth: stable code keys, readable Umami names, allowed data.
export const SCHEMA_VERSION = 2;
const event = (name, fields, purpose) => ({ name, fields: fields.split(' ').filter(Boolean), purpose });
export const EVENTS = Object.freeze({
  page_load: event('访问-内容加载完成', 'metric duration durationBucket outcome resultCount', '内容可用率、空数据率和加载耗时；不是页面浏览量'),
  feature_view: event('功能-有效曝光', 'feature outcome resultCount', '功能进入视口并连续可见 1 秒，每次内容访问去重'),
  tab_change: event('浏览-切换内容', 'tab category mode mapGameId mapId feature', '主动切换分区、地图和数据类别'),
  season_change: event('浏览-切换赛事', 'source', '主动选择赛事的需求'),
  open_match: event('导航-打开比赛', 'source', '从哪个入口进入哪场比赛'),
  open_upcoming: event('导航-打开赛前分析', 'source', '赛前分析入口转化'),
  open_team: event('导航-打开战队', 'source', '战队内容兴趣及入口'),
  open_player: event('导航-打开选手', 'source', '选手内容兴趣及入口'),
  back: event('导航-返回', 'source', '详情返回行为'),
  filter_change: event('分析-调整筛选', 'feature filter value role teamIds playerIds mapId heroId resultCount selectionCount', '用户主动选择的分析范围'),
  sort_change: event('分析-调整排序', 'feature metric order heroId', '最受关注的统计指标'),
  expand: event('分析-展开明细', 'feature expanded heroId mapId playerId metric', '深度分析使用情况'),
  compare: event('分析-选择对比', 'feature role playerIds playerNames selectionCount', '对比选择；至少两名选手时才算完整对比'),
  timeline_round: event('时间线-切换回合', 'round mapId mapGameId', '回合浏览需求'),
  timeline_filter: event('时间线-筛选事件', 'filter mapId mapGameId', '感兴趣的事件类型'),
  timeline_event: event('时间线-查看事件', 'eventType mapId mapGameId round', '主动打开时间线事件详情'),
  replay_expand: event('录像-展开代码', 'source expanded', '录像代码发现情况'),
  replay_copy: event('录像-复制代码结果', 'outcome mapId', '剪贴板操作结果，不收集录像代码'),
  vote_start: event('投票-提交支持', 'action', '投票尝试，区分首次与改投'),
  vote_result: event('投票-提交结果', 'action outcome duration durationBucket errorType', '投票成功率及错误类别'),
  export_start: event('导出-开始生成', 'feature type title transparent', '导出需求'),
  export_result: event('导出-生成结果', 'feature type title transparent outcome duration durationBucket errorType', '图片生成预览成功率，不代表保存到设备'),
  assistant_open: event('助手-打开', '', '助手入口使用'),
  assistant_context: event('助手-切换页面范围', 'withPage', '页面上下文使用'),
  assistant_send: event('助手-发送问题', 'inputType withPage turnBucket', '问题提交，不收集问题或对话内容'),
  assistant_result: event('助手-回答结果', 'inputType withPage outcome duration durationBucket firstTextMs errorType', '回答完成率、停止率、首字和总耗时'),
  api_error: event('质量-接口失败', 'resource method status errorType', '公开页面接口故障，去除原始 URL 与错误文本'),
});
export const PAGES = Object.freeze({
  '/visualize': { key: 'visualize_home', label: '赛事首页' },
  '/visualize/match-detail': { key: 'visualize_match_detail', label: '比赛详情' },
  '/visualize/upcoming-match': { key: 'visualize_upcoming_match_detail', label: '赛前分析' },
  '/visualize/team-detail': { key: 'visualize_team_detail', label: '战队详情' },
  '/visualize/player-detail': { key: 'visualize_player_detail', label: '选手详情' },
});
export const FIELDS = Object.freeze({
  seasonName: '赛事', seasonId: '赛事ID', stage: '赛段',
  matchName: '比赛', matchId: '比赛ID', matchDate: '比赛日期',
  teamName: '战队', teamId: '战队ID', team1Name: '对阵战队一', team2Name: '对阵战队二',
  playerName: '选手', playerId: '选手ID', heroName: '英雄', heroId: '英雄ID',
  mapName: '地图', mapId: '地图ID', mapGameId: '地图局ID',
  tab: '内容分区', category: '数据分类', mode: '展示模式', source: '入口',
  feature: '功能', filter: '筛选项', value: '筛选值', role: '职责',
  teamIds: '筛选战队', playerIds: '筛选选手', playerNames: '对比选手',
  selectionCount: '已选人数', resultCount: '结果数量', expanded: '展开状态',
  metric: '指标', order: '排序方向', duration: '耗时毫秒', durationBucket: '耗时区间', outcome: '结果',
  round: '回合', eventType: '事件类型', resource: '资源', action: '投票方式',
  type: '导出类型', title: '图表名称', transparent: '透明背景',
  withPage: '结合页面', inputType: '提问方式', turnBucket: '对话轮次', firstTextMs: '首字毫秒',
  errorType: '错误类别', method: '请求方式', status: 'HTTP状态',
});
export const CONTEXT_FIELDS = 'seasonName seasonId stage matchName matchId matchDate teamName teamId team1Name team2Name playerName playerId heroName heroId mapName mapId mapGameId'.split(' ');
export const LABELS = Object.freeze({
  recent: '赛程列表', stats: '赛事数据', overview: '赛事积分', overall: '全场总览',
  team: '战队', player: '选手', map: '地图', hero: '英雄', radar: '选手对比',
  players: '选手对比', maps: '地图分析', heroes: '英雄表现', history: '历史比赛',
  roster: '选手阵容', matches: '比赛记录', compositions: '阵容分析', bans: '英雄禁用',
  analysis: '数据分析', timeline: '逐事件时间线', data: '数据表', table: '数据表', chart: '图表',
  tank: '重装', damage: '输出', support: '支援', all: '全部',
  ascending: '升序', descending: '降序', pick: '选用次数', ban: '禁用次数', winRate: '胜率',
  control: '占领要点', hybrid: '攻击护送', escort: '运载目标', push: '机动推进', flashpoint: '闪点作战', clash: '攻防阵线',
  kd: 'K/D', kad: 'KA/D', elimsPer10: '每10分钟消灭', deathsPer10: '每10分钟死亡',
  assistsPer10: '每10分钟助攻', damagePer10: '每10分钟伤害', healingPer10: '每10分钟治疗',
  mitigationPer10: '每10分钟承伤', finalBlowsPer10: '每10分钟最后一击',
  fb: '最后一击', dmg: '伤害', heal: '治疗', time: '使用时长', duration: '时长',
  match_schedule: '赛程列表', recent_matches: '近期比赛', upcoming_matches: '未开赛列表',
  regular_season_board: '赛事积分榜', team_stats_chart: '战队排行榜', player_stats_chart: '选手排行榜',
  hero_overview: '英雄榜单', map_overview: '地图数据', visualize: '赛事首页',
  'player-detail': '选手详情', 'team-detail': '战队详情', 'match-detail': '比赛详情',
  kill: '击杀', death: '阵亡', last_blows: '最后一击', ultimates: '终极技能', ultimate: '大招',
  hero_selected: '选择英雄', hero_switch: '切换英雄', ultimate_used: '释放大招', ultimate_ready: '大招就绪', h2h: '历史交手',
  success: '成功', error: '失败', empty: '无数据', partial: '部分失败', completed: '完成',
  stopped: '主动停止', interrupted: '回答中断', preview: '预览已生成',
  first: '首次支持', change: '更改支持', repeat: '重复支持',
  starter: '预设问题', typed: '自主输入', timeout: '请求超时', network: '网络异常',
  http: '服务响应异常', unavailable: '服务不可用', unknown: '其他异常',
});
export const label = value => LABELS[String(value)] || String(value ?? '');
